### ISSUE TITLE
如何配置实现添加多个Api Server

### ISSUE THREAD

**Issue by zyknow** [luoyunchong/IGeekFan.AspNetCore.RapiDoc#16]

**Comment by luoyunchong** [comment]
```cs
builder.Services.AddSwaggerGen(c =>
{
    c.OperationFilter<RapiDocLableOperationFilter>();
    var filePath = Path.Combine(System.AppContext.BaseDirectory, $"{typeof(Program).Assembly.GetName().Name}.xml");
    c.IncludeXmlComments(filePath, true);
    c.SwaggerDoc("v1", new OpenApiInfo { Title = "AspNetCore6_RapiDemo", Version = "v1" });
    c.AddServer(new OpenApiServer()
    {
        Url = "https://localhost:7110",
        Description = "本地"
    });
    c.AddServer(new OpenApiServer()
    {
        Url = "https://igeekfan.cn:7110",
        Description = "服务器"
    });
});
```

**Comment by zyknow** [comment]
感谢回复，通过
"""
AddServer(new OpenApiServer()
    {
        Url = "https://igeekfan.cn:7110",
        Description = "服务器"
    });
"""
可以添加服务器
![image](https://github.com/luoyunchong/IGeekFan.AspNetCore.RapiDoc/assets/49929368/52e7b310-98bb-4b84-838f-2b23a5095118)


但是选中后没有任何效果，Api接口不会发生更新。

所有的swagger.json的url都是正确且可正常访问的。

**Comment by luoyunchong** [comment]
你要的不是apiserver

**Comment by zyknow** [comment]
在SwaggerUI中可以通过options.SwaggerEndpoint去添加多个节点，但是在UseRapiDoc进行相同的配置无效
可能是我理解的Api Server 不对
如果要达到一样的效果的话需要如何配置
![image](https://github.com/luoyunchong/IGeekFan.AspNetCore.RapiDoc/assets/49929368/0ad177d1-9050-4ee0-ac63-c9db8b135aae)
