### ISSUE TITLE
考虑支持身份认证功能吗？

### ISSUE THREAD

**Issue by Deali-Axy** [luoyunchong/IGeekFan.AspNetCore.RapiDoc#6]
大佬有考虑实现集成的身份认证功能吗（JWT）

**Comment by luoyunchong** [comment]
不是支持的吗。

**Comment by Deali-Axy** [comment]
可以像swagger这样输入JWT token吗？
![Snipaste_2022-03-02_00-08-38](https://user-images.githubusercontent.com/11494144/156204987-50c93402-b0d2-4918-acc4-b488a6383d73.png)

**Comment by luoyunchong** [comment]
![image](https://user-images.githubusercontent.com/18613266/156205958-6293cb24-991a-4f1c-8a0c-be01d057157a.png)


Ahtorization就是

**Comment by Deali-Axy** [comment]
谢谢！

刚发现这个功能是依赖`Swashbuckle.AspNetCore.Filters`的，之前我以为只有swagger能用…

还有一个问题，RapiDoc可以支持API分组功能吗？

类似这样：

![Snipaste_2022-03-02_09-29-54](https://user-images.githubusercontent.com/11494144/156277521-02734254-6122-4bc6-b317-a98aff54c9b8.png)

**Comment by luoyunchong** [comment]
只能手动输入，现在不支持。
